#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : gtk4
Version  : 4.5.1
Release  : 206
URL      : file:///aot/build/clearlinux/packages/gtk4/gtk4-v4.5.1.tar.gz
Source0  : file:///aot/build/clearlinux/packages/gtk4/gtk4-v4.5.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 LGPL-2.0 LGPL-2.1
Requires: gtk4-bin = %{version}-%{release}
Requires: gtk4-data = %{version}-%{release}
Requires: gtk4-lib = %{version}-%{release}
Requires: gtk4-locales = %{version}-%{release}
BuildRequires : Vulkan-Headers-dev
BuildRequires : Vulkan-Loader-dev
BuildRequires : atk
BuildRequires : atk-dev
BuildRequires : breeze
BuildRequires : breeze-gtk
BuildRequires : breeze-icons
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : bzip2-dev
BuildRequires : bzip2-staticdev
BuildRequires : cairo-dev
BuildRequires : colord-dev
BuildRequires : cups
BuildRequires : cups-dev
BuildRequires : curl
BuildRequires : curl-dev
BuildRequires : curl-lib
BuildRequires : dbus
BuildRequires : dbus-dev
BuildRequires : expat
BuildRequires : expat-dev
BuildRequires : expat-staticdev
BuildRequires : extra-cmake-modules-data
BuildRequires : fontconfig
BuildRequires : fontconfig-dev
BuildRequires : fonts-clear
BuildRequires : freetype
BuildRequires : freetype-dev
BuildRequires : fribidi-dev
BuildRequires : gdk-pixbuf
BuildRequires : gdk-pixbuf-dev
BuildRequires : glib
BuildRequires : glib-bin
BuildRequires : glib-dev
BuildRequires : glibc-dev
BuildRequires : glslang
BuildRequires : graphite
BuildRequires : graphite-dev
BuildRequires : gtk+-dev
BuildRequires : gtk4
BuildRequires : gtk4-dev
BuildRequires : harfbuzz-dev
BuildRequires : icu4c-dev
BuildRequires : icu4c-lib
BuildRequires : krb5
BuildRequires : krb5-dev
BuildRequires : libICE-dev
BuildRequires : libSM-dev
BuildRequires : libX11-data
BuildRequires : libX11-dev
BuildRequires : libX11-lib
BuildRequires : libXScrnSaver
BuildRequires : libXScrnSaver-dev
BuildRequires : libXScrnSaver-lib
BuildRequires : libXau-dev
BuildRequires : libXau-lib
BuildRequires : libXcomposite-dev
BuildRequires : libXcursor-dev
BuildRequires : libXcursor-lib
BuildRequires : libXdamage-dev
BuildRequires : libXdamage-lib
BuildRequires : libXdmcp-dev
BuildRequires : libXdmcp-lib
BuildRequires : libXext-dev
BuildRequires : libXext-lib
BuildRequires : libXfixes-dev
BuildRequires : libXfont2-dev
BuildRequires : libXft
BuildRequires : libXft-dev
BuildRequires : libXft-lib
BuildRequires : libXi-dev
BuildRequires : libXi-lib
BuildRequires : libXinerama-dev
BuildRequires : libXmu-dev
BuildRequires : libXpm-dev
BuildRequires : libXrandr-dev
BuildRequires : libXrender-dev
BuildRequires : libXrender-lib
BuildRequires : libXres-dev
BuildRequires : libXt-dev
BuildRequires : libXtst-dev
BuildRequires : libXtst-lib
BuildRequires : libXv-dev
BuildRequires : libXxf86vm-dev
BuildRequires : libXxf86vm-lib
BuildRequires : libgcrypt-dev
BuildRequires : libgit2
BuildRequires : libgit2-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libjpeg-turbo-dev32
BuildRequires : libjpeg-turbo-lib
BuildRequires : libjpeg-turbo-lib32
BuildRequires : libjpeg-turbo-staticdev
BuildRequires : libogg-dev
BuildRequires : libpng
BuildRequires : libpng-dev
BuildRequires : libpng-staticdev
BuildRequires : libpthread-stubs-dev
BuildRequires : librsvg-dev
BuildRequires : libsndfile-dev
BuildRequires : libvorbis-dev
BuildRequires : libwebp-dev
BuildRequires : libwebp-staticdev
BuildRequires : libxcb-dev
BuildRequires : libxcb-lib
BuildRequires : libxml2-dev
BuildRequires : libxml2-staticdev
BuildRequires : m4
BuildRequires : mesa-dev
BuildRequires : ninja
BuildRequires : openssh
BuildRequires : openssl-dev
BuildRequires : openssl-staticdev
BuildRequires : pango-dev
BuildRequires : pcre-dev
BuildRequires : pcre-staticdev
BuildRequires : pcre2-dev
BuildRequires : pcre2-staticdev
BuildRequires : pixman-dev
BuildRequires : pixman-staticdev
BuildRequires : pkg-config
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(gstreamer-player-1.0)
BuildRequires : pkgconfig(iso-codes)
BuildRequires : pkgconfig(librsvg-2.0)
BuildRequires : pygobject
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : requests
BuildRequires : sassc
BuildRequires : setxkbmap
BuildRequires : shared-mime-info
BuildRequires : shared-mime-info-dev
BuildRequires : tiff-dev
BuildRequires : tiff-staticdev
BuildRequires : util-linux
BuildRequires : util-linux-dev
BuildRequires : wayland
BuildRequires : wayland-dev
BuildRequires : xauth
BuildRequires : xclip
BuildRequires : xdg-dbus-proxy
BuildRequires : xdg-desktop-portal
BuildRequires : xdg-desktop-portal-dev
BuildRequires : xdg-desktop-portal-gtk
BuildRequires : xdg-desktop-portal-kde
BuildRequires : xdg-user-dirs
BuildRequires : xdg-user-dirs-gtk
BuildRequires : xdg-utils
BuildRequires : xdotool
BuildRequires : xdpyinfo
BuildRequires : xf86-input-libinput
BuildRequires : xf86-video-amdgpu
BuildRequires : xf86-video-ati
BuildRequires : xf86-video-fbdev
BuildRequires : xf86-video-nouveau
BuildRequires : xf86-video-qxl
BuildRequires : xf86-video-vboxvideo
BuildRequires : xf86-video-vesa
BuildRequires : xf86-video-vmware
BuildRequires : xfontsel
BuildRequires : xhost
BuildRequires : xinit
BuildRequires : xinput
BuildRequires : xkbcomp
BuildRequires : xkeyboard-config
BuildRequires : xkill
BuildRequires : xmodmap
BuildRequires : xorg-server
BuildRequires : xorg-server-dev
BuildRequires : xorgproto
BuildRequires : xorgproto-dev
BuildRequires : xprop
BuildRequires : xrandr
BuildRequires : xrdb
BuildRequires : xrdp
BuildRequires : xrestop
BuildRequires : xscreensaver
BuildRequires : xsel
BuildRequires : xset
BuildRequires : xsetroot
BuildRequires : xvfb-run
BuildRequires : xwd
BuildRequires : xwininfo
BuildRequires : xz
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Summary
-------
* To be able to use the latest/adequate version of sass, install sassc
* meson will regenerate the CSS every time you modify the SCSS files.
* Note that meson always builds out-of-tree, so the modified css files will
appear in your builddir.

%package bin
Summary: bin components for the gtk4 package.
Group: Binaries
Requires: gtk4-data = %{version}-%{release}

%description bin
bin components for the gtk4 package.


%package data
Summary: data components for the gtk4 package.
Group: Data

%description data
data components for the gtk4 package.


%package dev
Summary: dev components for the gtk4 package.
Group: Development
Requires: gtk4-lib = %{version}-%{release}
Requires: gtk4-bin = %{version}-%{release}
Requires: gtk4-data = %{version}-%{release}
Provides: gtk4-devel = %{version}-%{release}
Requires: gtk4 = %{version}-%{release}

%description dev
dev components for the gtk4 package.


%package lib
Summary: lib components for the gtk4 package.
Group: Libraries
Requires: gtk4-data = %{version}-%{release}

%description lib
lib components for the gtk4 package.


%package locales
Summary: locales components for the gtk4 package.
Group: Default

%description locales
locales components for the gtk4 package.


%prep
%setup -q -n gtk4
cd %{_builddir}/gtk4

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1640471600
export GCC_IGNORE_WERROR=1
## altflags1 content
## altflags1
unset ASFLAGS
export CFLAGS="-g3 -ggdb -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
export ASMFLAGS="-g3 -ggdb -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
## -fno-tree-vectorize: disable -ftree-vectorize thus disable -ftree-loop-vectorize and -ftree-slp-vectorize -fopt-info-vec
## -Ofast -ffast-math
## -funroll-loops maybe dangerous
## -Wl,-z,max-page-size=0x1000
## -pthread -lpthread
## -Wl,-Bsymbolic-functions
export CXXFLAGS="-g3 -ggdb -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export FCFLAGS="-g3 -ggdb -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
export FFLAGS="-g3 -ggdb -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export LDFLAGS="-g3 -ggdb -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
#
export PKG_CONFIG_PATH="/usr/lib64/pkgconfig:/usr/share/pkgconfig"
#
export LD_LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export PATH="/usr/lib64/ccache/bin:/usr/local/cuda/bin:/usr/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
#
export CPATH="/usr/local/cuda/include"
#
export DISPLAY=:0
export __GL_SYNC_TO_VBLANK=1
export __GL_SYNC_DISPLAY_DEVICE=HDMI-0
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=HDMI-0
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH="/usr/share/defaults/fonts"
export GTK_IM_MODULE="xim"
export QT_IM_MODULE="cedilla"
export FREETYPE_PROPERTIES="truetype:interpreter-version=40"
export PLASMA_USE_QT_SCALING=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
## altflags1 end
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" LIBS="$LIBS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Ddefault_library=both  -Ddefault_library=both \
-Dgtk_doc=false \
-Dx11-backend=true \
-Dwayland-backend=false \
-Dbroadway-backend=false \
-Dwin32-backend=false \
-Dmacos-backend=false \
-Df16c=enabled \
-Dintrospection=enabled \
-Dbuild-examples=false \
-Dinstall-tests=false \
-Dbuild-tests=false builddir
ninja --verbose %{?_smp_mflags} -C builddir


%install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gtk40-properties
%find_lang gtk40
## install_append content
install -dm 0755 %{buildroot}/usr/lib64/haswell/ || :
cp --archive %{buildroot}/usr/lib64/lib*.so* %{buildroot}/usr/lib64/haswell/ || :
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gtk4-builder-tool
/usr/bin/gtk4-demo
/usr/bin/gtk4-demo-application
/usr/bin/gtk4-encode-symbolic-svg
/usr/bin/gtk4-icon-browser
/usr/bin/gtk4-launch
/usr/bin/gtk4-print-editor
/usr/bin/gtk4-query-settings
/usr/bin/gtk4-update-icon-cache
/usr/bin/gtk4-widget-factory

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Gdk-4.0.typelib
/usr/lib64/girepository-1.0/GdkX11-4.0.typelib
/usr/lib64/girepository-1.0/Gsk-4.0.typelib
/usr/lib64/girepository-1.0/Gtk-4.0.typelib
/usr/share/applications/org.gtk.Demo4.desktop
/usr/share/applications/org.gtk.IconBrowser4.desktop
/usr/share/applications/org.gtk.PrintEditor4.desktop
/usr/share/applications/org.gtk.WidgetFactory4.desktop
/usr/share/gettext/its/gtk4builder.its
/usr/share/gettext/its/gtk4builder.loc
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gtk.Demo4.gschema.xml
/usr/share/glib-2.0/schemas/org.gtk.gtk4.Settings.ColorChooser.gschema.xml
/usr/share/glib-2.0/schemas/org.gtk.gtk4.Settings.Debug.gschema.xml
/usr/share/glib-2.0/schemas/org.gtk.gtk4.Settings.EmojiChooser.gschema.xml
/usr/share/glib-2.0/schemas/org.gtk.gtk4.Settings.FileChooser.gschema.xml
/usr/share/gtk-4.0/emoji/de.gresource
/usr/share/gtk-4.0/emoji/es.gresource
/usr/share/gtk-4.0/emoji/fr.gresource
/usr/share/gtk-4.0/emoji/zh.gresource
/usr/share/gtk-4.0/gtk4builder.rng
/usr/share/gtk-4.0/valgrind/gtk.supp
/usr/share/icons/hicolor/scalable/apps/org.gtk.Demo4.svg
/usr/share/icons/hicolor/scalable/apps/org.gtk.IconBrowser4.svg
/usr/share/icons/hicolor/scalable/apps/org.gtk.PrintEditor4.Devel.svg
/usr/share/icons/hicolor/scalable/apps/org.gtk.PrintEditor4.svg
/usr/share/icons/hicolor/scalable/apps/org.gtk.WidgetFactory4.svg
/usr/share/icons/hicolor/symbolic/apps/org.gtk.Demo4-symbolic.svg
/usr/share/icons/hicolor/symbolic/apps/org.gtk.IconBrowser4-symbolic.svg
/usr/share/icons/hicolor/symbolic/apps/org.gtk.PrintEditor4-symbolic.svg
/usr/share/icons/hicolor/symbolic/apps/org.gtk.WidgetFactory4-symbolic.svg
/usr/share/metainfo/org.gtk.Demo4.appdata.xml
/usr/share/metainfo/org.gtk.IconBrowser4.appdata.xml
/usr/share/metainfo/org.gtk.PrintEditor4.appdata.xml
/usr/share/metainfo/org.gtk.WidgetFactory4.appdata.xml

%files dev
%defattr(-,root,root,-)
/usr/include/gtk-4.0/gdk/gdk-autocleanup.h
/usr/include/gtk-4.0/gdk/gdk.h
/usr/include/gtk-4.0/gdk/gdkapplaunchcontext.h
/usr/include/gtk-4.0/gdk/gdkcairo.h
/usr/include/gtk-4.0/gdk/gdkcairocontext.h
/usr/include/gtk-4.0/gdk/gdkclipboard.h
/usr/include/gtk-4.0/gdk/gdkconfig.h
/usr/include/gtk-4.0/gdk/gdkcontentdeserializer.h
/usr/include/gtk-4.0/gdk/gdkcontentformats.h
/usr/include/gtk-4.0/gdk/gdkcontentprovider.h
/usr/include/gtk-4.0/gdk/gdkcontentproviderimpl.h
/usr/include/gtk-4.0/gdk/gdkcontentserializer.h
/usr/include/gtk-4.0/gdk/gdkcursor.h
/usr/include/gtk-4.0/gdk/gdkdevice.h
/usr/include/gtk-4.0/gdk/gdkdevicepad.h
/usr/include/gtk-4.0/gdk/gdkdevicetool.h
/usr/include/gtk-4.0/gdk/gdkdisplay.h
/usr/include/gtk-4.0/gdk/gdkdisplaymanager.h
/usr/include/gtk-4.0/gdk/gdkdrag.h
/usr/include/gtk-4.0/gdk/gdkdragsurface.h
/usr/include/gtk-4.0/gdk/gdkdrawcontext.h
/usr/include/gtk-4.0/gdk/gdkdrop.h
/usr/include/gtk-4.0/gdk/gdkenums.h
/usr/include/gtk-4.0/gdk/gdkenumtypes.h
/usr/include/gtk-4.0/gdk/gdkevents.h
/usr/include/gtk-4.0/gdk/gdkframeclock.h
/usr/include/gtk-4.0/gdk/gdkframetimings.h
/usr/include/gtk-4.0/gdk/gdkglcontext.h
/usr/include/gtk-4.0/gdk/gdkgltexture.h
/usr/include/gtk-4.0/gdk/gdkkeys.h
/usr/include/gtk-4.0/gdk/gdkkeysyms.h
/usr/include/gtk-4.0/gdk/gdkmemorytexture.h
/usr/include/gtk-4.0/gdk/gdkmonitor.h
/usr/include/gtk-4.0/gdk/gdkpaintable.h
/usr/include/gtk-4.0/gdk/gdkpango.h
/usr/include/gtk-4.0/gdk/gdkpixbuf.h
/usr/include/gtk-4.0/gdk/gdkpopup.h
/usr/include/gtk-4.0/gdk/gdkpopuplayout.h
/usr/include/gtk-4.0/gdk/gdkrectangle.h
/usr/include/gtk-4.0/gdk/gdkrgba.h
/usr/include/gtk-4.0/gdk/gdkseat.h
/usr/include/gtk-4.0/gdk/gdksnapshot.h
/usr/include/gtk-4.0/gdk/gdksurface.h
/usr/include/gtk-4.0/gdk/gdktexture.h
/usr/include/gtk-4.0/gdk/gdktoplevel.h
/usr/include/gtk-4.0/gdk/gdktoplevellayout.h
/usr/include/gtk-4.0/gdk/gdktoplevelsize.h
/usr/include/gtk-4.0/gdk/gdktypes.h
/usr/include/gtk-4.0/gdk/gdkversionmacros.h
/usr/include/gtk-4.0/gdk/gdkvulkancontext.h
/usr/include/gtk-4.0/gdk/x11/gdkx-autocleanups.h
/usr/include/gtk-4.0/gdk/x11/gdkx.h
/usr/include/gtk-4.0/gdk/x11/gdkx11applaunchcontext.h
/usr/include/gtk-4.0/gdk/x11/gdkx11device-xi2.h
/usr/include/gtk-4.0/gdk/x11/gdkx11device.h
/usr/include/gtk-4.0/gdk/x11/gdkx11devicemanager-xi2.h
/usr/include/gtk-4.0/gdk/x11/gdkx11devicemanager.h
/usr/include/gtk-4.0/gdk/x11/gdkx11display.h
/usr/include/gtk-4.0/gdk/x11/gdkx11dnd.h
/usr/include/gtk-4.0/gdk/x11/gdkx11glcontext.h
/usr/include/gtk-4.0/gdk/x11/gdkx11monitor.h
/usr/include/gtk-4.0/gdk/x11/gdkx11property.h
/usr/include/gtk-4.0/gdk/x11/gdkx11screen.h
/usr/include/gtk-4.0/gdk/x11/gdkx11selection.h
/usr/include/gtk-4.0/gdk/x11/gdkx11surface.h
/usr/include/gtk-4.0/gdk/x11/gdkx11utils.h
/usr/include/gtk-4.0/gsk/gl/gskglrenderer.h
/usr/include/gtk-4.0/gsk/gsk-autocleanup.h
/usr/include/gtk-4.0/gsk/gsk.h
/usr/include/gtk-4.0/gsk/gskcairorenderer.h
/usr/include/gtk-4.0/gsk/gskenums.h
/usr/include/gtk-4.0/gsk/gskenumtypes.h
/usr/include/gtk-4.0/gsk/gskglshader.h
/usr/include/gtk-4.0/gsk/gskrenderer.h
/usr/include/gtk-4.0/gsk/gskrendernode.h
/usr/include/gtk-4.0/gsk/gskroundedrect.h
/usr/include/gtk-4.0/gsk/gsktransform.h
/usr/include/gtk-4.0/gsk/gsktypes.h
/usr/include/gtk-4.0/gtk/css/gtkcss.h
/usr/include/gtk-4.0/gtk/css/gtkcssenums.h
/usr/include/gtk-4.0/gtk/css/gtkcssenumtypes.h
/usr/include/gtk-4.0/gtk/css/gtkcsserror.h
/usr/include/gtk-4.0/gtk/css/gtkcsslocation.h
/usr/include/gtk-4.0/gtk/css/gtkcsssection.h
/usr/include/gtk-4.0/gtk/gtk-autocleanups.h
/usr/include/gtk-4.0/gtk/gtk.h
/usr/include/gtk-4.0/gtk/gtkaboutdialog.h
/usr/include/gtk-4.0/gtk/gtkaccelgroup.h
/usr/include/gtk-4.0/gtk/gtkaccessible.h
/usr/include/gtk-4.0/gtk/gtkactionable.h
/usr/include/gtk-4.0/gtk/gtkactionbar.h
/usr/include/gtk-4.0/gtk/gtkadjustment.h
/usr/include/gtk-4.0/gtk/gtkappchooser.h
/usr/include/gtk-4.0/gtk/gtkappchooserbutton.h
/usr/include/gtk-4.0/gtk/gtkappchooserdialog.h
/usr/include/gtk-4.0/gtk/gtkappchooserwidget.h
/usr/include/gtk-4.0/gtk/gtkapplication.h
/usr/include/gtk-4.0/gtk/gtkapplicationwindow.h
/usr/include/gtk-4.0/gtk/gtkaspectframe.h
/usr/include/gtk-4.0/gtk/gtkassistant.h
/usr/include/gtk-4.0/gtk/gtkatcontext.h
/usr/include/gtk-4.0/gtk/gtkbinlayout.h
/usr/include/gtk-4.0/gtk/gtkbitset.h
/usr/include/gtk-4.0/gtk/gtkbookmarklist.h
/usr/include/gtk-4.0/gtk/gtkboolfilter.h
/usr/include/gtk-4.0/gtk/gtkborder.h
/usr/include/gtk-4.0/gtk/gtkbox.h
/usr/include/gtk-4.0/gtk/gtkboxlayout.h
/usr/include/gtk-4.0/gtk/gtkbuildable.h
/usr/include/gtk-4.0/gtk/gtkbuilder.h
/usr/include/gtk-4.0/gtk/gtkbuilderlistitemfactory.h
/usr/include/gtk-4.0/gtk/gtkbuilderscope.h
/usr/include/gtk-4.0/gtk/gtkbutton.h
/usr/include/gtk-4.0/gtk/gtkcalendar.h
/usr/include/gtk-4.0/gtk/gtkcellarea.h
/usr/include/gtk-4.0/gtk/gtkcellareabox.h
/usr/include/gtk-4.0/gtk/gtkcellareacontext.h
/usr/include/gtk-4.0/gtk/gtkcelleditable.h
/usr/include/gtk-4.0/gtk/gtkcelllayout.h
/usr/include/gtk-4.0/gtk/gtkcellrenderer.h
/usr/include/gtk-4.0/gtk/gtkcellrendereraccel.h
/usr/include/gtk-4.0/gtk/gtkcellrenderercombo.h
/usr/include/gtk-4.0/gtk/gtkcellrendererpixbuf.h
/usr/include/gtk-4.0/gtk/gtkcellrendererprogress.h
/usr/include/gtk-4.0/gtk/gtkcellrendererspin.h
/usr/include/gtk-4.0/gtk/gtkcellrendererspinner.h
/usr/include/gtk-4.0/gtk/gtkcellrenderertext.h
/usr/include/gtk-4.0/gtk/gtkcellrenderertoggle.h
/usr/include/gtk-4.0/gtk/gtkcellview.h
/usr/include/gtk-4.0/gtk/gtkcenterbox.h
/usr/include/gtk-4.0/gtk/gtkcenterlayout.h
/usr/include/gtk-4.0/gtk/gtkcheckbutton.h
/usr/include/gtk-4.0/gtk/gtkcolorbutton.h
/usr/include/gtk-4.0/gtk/gtkcolorchooser.h
/usr/include/gtk-4.0/gtk/gtkcolorchooserdialog.h
/usr/include/gtk-4.0/gtk/gtkcolorchooserwidget.h
/usr/include/gtk-4.0/gtk/gtkcolorutils.h
/usr/include/gtk-4.0/gtk/gtkcolumnview.h
/usr/include/gtk-4.0/gtk/gtkcolumnviewcolumn.h
/usr/include/gtk-4.0/gtk/gtkcombobox.h
/usr/include/gtk-4.0/gtk/gtkcomboboxtext.h
/usr/include/gtk-4.0/gtk/gtkconstraint.h
/usr/include/gtk-4.0/gtk/gtkconstraintguide.h
/usr/include/gtk-4.0/gtk/gtkconstraintlayout.h
/usr/include/gtk-4.0/gtk/gtkcssprovider.h
/usr/include/gtk-4.0/gtk/gtkcustomfilter.h
/usr/include/gtk-4.0/gtk/gtkcustomlayout.h
/usr/include/gtk-4.0/gtk/gtkcustomsorter.h
/usr/include/gtk-4.0/gtk/gtkdebug.h
/usr/include/gtk-4.0/gtk/gtkdialog.h
/usr/include/gtk-4.0/gtk/gtkdirectorylist.h
/usr/include/gtk-4.0/gtk/gtkdragicon.h
/usr/include/gtk-4.0/gtk/gtkdragsource.h
/usr/include/gtk-4.0/gtk/gtkdrawingarea.h
/usr/include/gtk-4.0/gtk/gtkdropcontrollermotion.h
/usr/include/gtk-4.0/gtk/gtkdropdown.h
/usr/include/gtk-4.0/gtk/gtkdroptarget.h
/usr/include/gtk-4.0/gtk/gtkdroptargetasync.h
/usr/include/gtk-4.0/gtk/gtkeditable.h
/usr/include/gtk-4.0/gtk/gtkeditablelabel.h
/usr/include/gtk-4.0/gtk/gtkemojichooser.h
/usr/include/gtk-4.0/gtk/gtkentry.h
/usr/include/gtk-4.0/gtk/gtkentrybuffer.h
/usr/include/gtk-4.0/gtk/gtkentrycompletion.h
/usr/include/gtk-4.0/gtk/gtkenums.h
/usr/include/gtk-4.0/gtk/gtkeventcontroller.h
/usr/include/gtk-4.0/gtk/gtkeventcontrollerfocus.h
/usr/include/gtk-4.0/gtk/gtkeventcontrollerkey.h
/usr/include/gtk-4.0/gtk/gtkeventcontrollerlegacy.h
/usr/include/gtk-4.0/gtk/gtkeventcontrollermotion.h
/usr/include/gtk-4.0/gtk/gtkeventcontrollerscroll.h
/usr/include/gtk-4.0/gtk/gtkexpander.h
/usr/include/gtk-4.0/gtk/gtkexpression.h
/usr/include/gtk-4.0/gtk/gtkfilechooser.h
/usr/include/gtk-4.0/gtk/gtkfilechooserdialog.h
/usr/include/gtk-4.0/gtk/gtkfilechoosernative.h
/usr/include/gtk-4.0/gtk/gtkfilechooserwidget.h
/usr/include/gtk-4.0/gtk/gtkfilefilter.h
/usr/include/gtk-4.0/gtk/gtkfilter.h
/usr/include/gtk-4.0/gtk/gtkfilterlistmodel.h
/usr/include/gtk-4.0/gtk/gtkfixed.h
/usr/include/gtk-4.0/gtk/gtkfixedlayout.h
/usr/include/gtk-4.0/gtk/gtkflattenlistmodel.h
/usr/include/gtk-4.0/gtk/gtkflowbox.h
/usr/include/gtk-4.0/gtk/gtkfontbutton.h
/usr/include/gtk-4.0/gtk/gtkfontchooser.h
/usr/include/gtk-4.0/gtk/gtkfontchooserdialog.h
/usr/include/gtk-4.0/gtk/gtkfontchooserwidget.h
/usr/include/gtk-4.0/gtk/gtkframe.h
/usr/include/gtk-4.0/gtk/gtkgesture.h
/usr/include/gtk-4.0/gtk/gtkgestureclick.h
/usr/include/gtk-4.0/gtk/gtkgesturedrag.h
/usr/include/gtk-4.0/gtk/gtkgesturelongpress.h
/usr/include/gtk-4.0/gtk/gtkgesturepan.h
/usr/include/gtk-4.0/gtk/gtkgesturerotate.h
/usr/include/gtk-4.0/gtk/gtkgesturesingle.h
/usr/include/gtk-4.0/gtk/gtkgesturestylus.h
/usr/include/gtk-4.0/gtk/gtkgestureswipe.h
/usr/include/gtk-4.0/gtk/gtkgesturezoom.h
/usr/include/gtk-4.0/gtk/gtkglarea.h
/usr/include/gtk-4.0/gtk/gtkgrid.h
/usr/include/gtk-4.0/gtk/gtkgridlayout.h
/usr/include/gtk-4.0/gtk/gtkgridview.h
/usr/include/gtk-4.0/gtk/gtkheaderbar.h
/usr/include/gtk-4.0/gtk/gtkicontheme.h
/usr/include/gtk-4.0/gtk/gtkiconview.h
/usr/include/gtk-4.0/gtk/gtkimage.h
/usr/include/gtk-4.0/gtk/gtkimcontext.h
/usr/include/gtk-4.0/gtk/gtkimcontextsimple.h
/usr/include/gtk-4.0/gtk/gtkimmodule.h
/usr/include/gtk-4.0/gtk/gtkimmulticontext.h
/usr/include/gtk-4.0/gtk/gtkinfobar.h
/usr/include/gtk-4.0/gtk/gtklabel.h
/usr/include/gtk-4.0/gtk/gtklayoutchild.h
/usr/include/gtk-4.0/gtk/gtklayoutmanager.h
/usr/include/gtk-4.0/gtk/gtklevelbar.h
/usr/include/gtk-4.0/gtk/gtklinkbutton.h
/usr/include/gtk-4.0/gtk/gtklistbase.h
/usr/include/gtk-4.0/gtk/gtklistbox.h
/usr/include/gtk-4.0/gtk/gtklistitem.h
/usr/include/gtk-4.0/gtk/gtklistitemfactory.h
/usr/include/gtk-4.0/gtk/gtkliststore.h
/usr/include/gtk-4.0/gtk/gtklistview.h
/usr/include/gtk-4.0/gtk/gtklockbutton.h
/usr/include/gtk-4.0/gtk/gtkmain.h
/usr/include/gtk-4.0/gtk/gtkmaplistmodel.h
/usr/include/gtk-4.0/gtk/gtkmediacontrols.h
/usr/include/gtk-4.0/gtk/gtkmediafile.h
/usr/include/gtk-4.0/gtk/gtkmediastream.h
/usr/include/gtk-4.0/gtk/gtkmenubutton.h
/usr/include/gtk-4.0/gtk/gtkmessagedialog.h
/usr/include/gtk-4.0/gtk/gtkmountoperation.h
/usr/include/gtk-4.0/gtk/gtkmultifilter.h
/usr/include/gtk-4.0/gtk/gtkmultiselection.h
/usr/include/gtk-4.0/gtk/gtkmultisorter.h
/usr/include/gtk-4.0/gtk/gtknative.h
/usr/include/gtk-4.0/gtk/gtknativedialog.h
/usr/include/gtk-4.0/gtk/gtknoselection.h
/usr/include/gtk-4.0/gtk/gtknotebook.h
/usr/include/gtk-4.0/gtk/gtknumericsorter.h
/usr/include/gtk-4.0/gtk/gtkorientable.h
/usr/include/gtk-4.0/gtk/gtkoverlay.h
/usr/include/gtk-4.0/gtk/gtkoverlaylayout.h
/usr/include/gtk-4.0/gtk/gtkpadcontroller.h
/usr/include/gtk-4.0/gtk/gtkpagesetup.h
/usr/include/gtk-4.0/gtk/gtkpaned.h
/usr/include/gtk-4.0/gtk/gtkpapersize.h
/usr/include/gtk-4.0/gtk/gtkpasswordentry.h
/usr/include/gtk-4.0/gtk/gtkpasswordentrybuffer.h
/usr/include/gtk-4.0/gtk/gtkpicture.h
/usr/include/gtk-4.0/gtk/gtkpopover.h
/usr/include/gtk-4.0/gtk/gtkpopovermenu.h
/usr/include/gtk-4.0/gtk/gtkpopovermenubar.h
/usr/include/gtk-4.0/gtk/gtkprintcontext.h
/usr/include/gtk-4.0/gtk/gtkprintoperation.h
/usr/include/gtk-4.0/gtk/gtkprintoperationpreview.h
/usr/include/gtk-4.0/gtk/gtkprintsettings.h
/usr/include/gtk-4.0/gtk/gtkprogressbar.h
/usr/include/gtk-4.0/gtk/gtkrange.h
/usr/include/gtk-4.0/gtk/gtkrecentmanager.h
/usr/include/gtk-4.0/gtk/gtkrender.h
/usr/include/gtk-4.0/gtk/gtkrevealer.h
/usr/include/gtk-4.0/gtk/gtkroot.h
/usr/include/gtk-4.0/gtk/gtkscale.h
/usr/include/gtk-4.0/gtk/gtkscalebutton.h
/usr/include/gtk-4.0/gtk/gtkscrollable.h
/usr/include/gtk-4.0/gtk/gtkscrollbar.h
/usr/include/gtk-4.0/gtk/gtkscrolledwindow.h
/usr/include/gtk-4.0/gtk/gtksearchbar.h
/usr/include/gtk-4.0/gtk/gtksearchentry.h
/usr/include/gtk-4.0/gtk/gtkselectionfiltermodel.h
/usr/include/gtk-4.0/gtk/gtkselectionmodel.h
/usr/include/gtk-4.0/gtk/gtkseparator.h
/usr/include/gtk-4.0/gtk/gtksettings.h
/usr/include/gtk-4.0/gtk/gtkshortcut.h
/usr/include/gtk-4.0/gtk/gtkshortcutaction.h
/usr/include/gtk-4.0/gtk/gtkshortcutcontroller.h
/usr/include/gtk-4.0/gtk/gtkshortcutlabel.h
/usr/include/gtk-4.0/gtk/gtkshortcutmanager.h
/usr/include/gtk-4.0/gtk/gtkshortcutsgroup.h
/usr/include/gtk-4.0/gtk/gtkshortcutssection.h
/usr/include/gtk-4.0/gtk/gtkshortcutsshortcut.h
/usr/include/gtk-4.0/gtk/gtkshortcutswindow.h
/usr/include/gtk-4.0/gtk/gtkshortcuttrigger.h
/usr/include/gtk-4.0/gtk/gtkshow.h
/usr/include/gtk-4.0/gtk/gtksignallistitemfactory.h
/usr/include/gtk-4.0/gtk/gtksingleselection.h
/usr/include/gtk-4.0/gtk/gtksizegroup.h
/usr/include/gtk-4.0/gtk/gtksizerequest.h
/usr/include/gtk-4.0/gtk/gtkslicelistmodel.h
/usr/include/gtk-4.0/gtk/gtksnapshot.h
/usr/include/gtk-4.0/gtk/gtksorter.h
/usr/include/gtk-4.0/gtk/gtksortlistmodel.h
/usr/include/gtk-4.0/gtk/gtkspinbutton.h
/usr/include/gtk-4.0/gtk/gtkspinner.h
/usr/include/gtk-4.0/gtk/gtkstack.h
/usr/include/gtk-4.0/gtk/gtkstacksidebar.h
/usr/include/gtk-4.0/gtk/gtkstackswitcher.h
/usr/include/gtk-4.0/gtk/gtkstatusbar.h
/usr/include/gtk-4.0/gtk/gtkstringfilter.h
/usr/include/gtk-4.0/gtk/gtkstringlist.h
/usr/include/gtk-4.0/gtk/gtkstringsorter.h
/usr/include/gtk-4.0/gtk/gtkstylecontext.h
/usr/include/gtk-4.0/gtk/gtkstyleprovider.h
/usr/include/gtk-4.0/gtk/gtkswitch.h
/usr/include/gtk-4.0/gtk/gtksymbolicpaintable.h
/usr/include/gtk-4.0/gtk/gtktestatcontext.h
/usr/include/gtk-4.0/gtk/gtktestutils.h
/usr/include/gtk-4.0/gtk/gtktext.h
/usr/include/gtk-4.0/gtk/gtktextbuffer.h
/usr/include/gtk-4.0/gtk/gtktextchild.h
/usr/include/gtk-4.0/gtk/gtktextiter.h
/usr/include/gtk-4.0/gtk/gtktextmark.h
/usr/include/gtk-4.0/gtk/gtktexttag.h
/usr/include/gtk-4.0/gtk/gtktexttagtable.h
/usr/include/gtk-4.0/gtk/gtktextview.h
/usr/include/gtk-4.0/gtk/gtktogglebutton.h
/usr/include/gtk-4.0/gtk/gtktooltip.h
/usr/include/gtk-4.0/gtk/gtktreednd.h
/usr/include/gtk-4.0/gtk/gtktreeexpander.h
/usr/include/gtk-4.0/gtk/gtktreelistmodel.h
/usr/include/gtk-4.0/gtk/gtktreelistrowsorter.h
/usr/include/gtk-4.0/gtk/gtktreemodel.h
/usr/include/gtk-4.0/gtk/gtktreemodelfilter.h
/usr/include/gtk-4.0/gtk/gtktreemodelsort.h
/usr/include/gtk-4.0/gtk/gtktreeselection.h
/usr/include/gtk-4.0/gtk/gtktreesortable.h
/usr/include/gtk-4.0/gtk/gtktreestore.h
/usr/include/gtk-4.0/gtk/gtktreeview.h
/usr/include/gtk-4.0/gtk/gtktreeviewcolumn.h
/usr/include/gtk-4.0/gtk/gtktypebuiltins.h
/usr/include/gtk-4.0/gtk/gtktypes.h
/usr/include/gtk-4.0/gtk/gtkversion.h
/usr/include/gtk-4.0/gtk/gtkvideo.h
/usr/include/gtk-4.0/gtk/gtkviewport.h
/usr/include/gtk-4.0/gtk/gtkvolumebutton.h
/usr/include/gtk-4.0/gtk/gtkwidget.h
/usr/include/gtk-4.0/gtk/gtkwidgetpaintable.h
/usr/include/gtk-4.0/gtk/gtkwindow.h
/usr/include/gtk-4.0/gtk/gtkwindowcontrols.h
/usr/include/gtk-4.0/gtk/gtkwindowgroup.h
/usr/include/gtk-4.0/gtk/gtkwindowhandle.h
/usr/include/gtk-4.0/unix-print/gtk/gtkpagesetupunixdialog.h
/usr/include/gtk-4.0/unix-print/gtk/gtkprinter.h
/usr/include/gtk-4.0/unix-print/gtk/gtkprintjob.h
/usr/include/gtk-4.0/unix-print/gtk/gtkprintunixdialog.h
/usr/include/gtk-4.0/unix-print/gtk/gtkunixprint-autocleanups.h
/usr/include/gtk-4.0/unix-print/gtk/gtkunixprint.h
/usr/lib64/gtk-4.0/4.0.0/media/libmedia-gstreamer.so
/usr/lib64/gtk-4.0/4.0.0/printbackends/libprintbackend-cups.so
/usr/lib64/gtk-4.0/4.0.0/printbackends/libprintbackend-file.so
/usr/lib64/haswell/libgtk-4.so
/usr/lib64/libgtk-4.so
/usr/lib64/pkgconfig/gtk4-unix-print.pc
/usr/lib64/pkgconfig/gtk4-x11.pc
/usr/lib64/pkgconfig/gtk4.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/haswell/libgtk-4.so.1
/usr/lib64/haswell/libgtk-4.so.1.501.0
/usr/lib64/libgtk-4.so.1
/usr/lib64/libgtk-4.so.1.501.0

%files locales -f gtk40-properties.lang -f gtk40.lang
%defattr(-,root,root,-)
